echo "" > "data/rdf-file.ttl"
cat "ontology/usage_ontology.ttl" >> "data/rdf-file.ttl"
# cat "data/IDEZAR/Barrios/rdf/"*.nt >> "data/rdf-file.ttl"
# cat "data/IDEZAR/Distritos/rdf/"*.nt >> "data/rdf-file.ttl"
# cat "data/ZGZ/Residencial/rdf/"*.nt >> "data/rdf-file.ttl"
# cat "data/ZGZ/Industrial/rdf/"*.nt >> "data/rdf-file.ttl"
cat "data/ZGZ/Institucional_y_servicios/rdf/"*.nt >> "data/rdf-file.ttl"
# cat "data/ZGZ/"*.nt >> "data/rdf-file.ttl"