PREFIX s4city: <https://saref.etsi.org/saref4city/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX bigg: <http://bigg-project.eu/ld/ontology#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name (count(DISTINCT ?feature) as ?wktLabel) #?cell #
WHERE{
  ?feature a geo:Feature;
           geo:hasGeometry/geo:asWKT ?cell.
    FILTER (geof:sfWithin(?cell,?wkt))
   {
   select * where { 
       ?neighbourhood a s4city:Neighbourhood;
                      rdfs:label ?name;
                      geo:hasGeometry/geo:asWKT ?wkt.
   }
   }
} GROUP BY ?name