PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX s4city: <https://saref.etsi.org/saref4city/>
PREFIX saref: <https://saref.etsi.org/core/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX usage-o: <http://usage-project.eu/ld/ontology#>
SELECT * WHERE {
  ?kpia a s4city:KeyPerformanceIndicatorAssessment;
       saref:hasValue ?kpiaValue;
       saref:isMeasuredIn ?kpiaValueUnit;
       s4city:quantifiesKPI usage-o:CH4Scope1Emissions; #?kpi;
       s4city:refersToFeature ?feature.
  ?feature a geo:Feature;
           geo:hasGeometry ?geometry.
  ?geometry a geo:Geometry;
            geo:asWKT ?wkt.
  BIND( CONCAT("portland, ", str(?kpiaValue/0.1)) as ?wktColor) #CO2 786  CH4 0.1
} 